FROM python:3.11-slim

# Set workdir
WORKDIR /app

# Install dependencies
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the app
COPY backend/ .

# Expose FastAPI on port 8000
EXPOSE 8003

# Run the app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8003"]
