version = 0.1
[default.deploy.parameters]
stack_name = "agent-app"
resolve_s3 = true
s3_prefix = "agent-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "OpenAIApiKey=\"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\" NeonApiKey=\"napi_wfiu24fhktjtfylrpn4wi6rq02uy0le6r11t9s4oz02q9pctj7nlez44gwvlvs56\" McpServerUrl=\"https://mcp.neon.tech/sse\""
image_repositories = []
