AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: MCPAgent Lambda function with FastAPI + Mangum

Parameters:
  OpenAIApiKey:
    Type: String
    Description: OpenAI API Key

  NeonApiKey:
    Type: String
    Description: Neon API Key

  McpServerUrl:
    Type: String
    Description: MCP Server URL
    Default: https://mcp.neon.tech/sse

Resources:
  MCPAgentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: main.handler
      Runtime: python3.10
      Timeout: 300
      MemorySize: 1024
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIApiKey
          NEON_API_KEY: !Ref NeonApiKey
          MCP_SERVER_URL: !Ref McpServerUrl
      Events:
        ApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: GET
        ApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiEndpoint:
    Description: "Invoke URL of the Lambda function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  
  FunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt MCPAgentFunction.Arn
