      - name: Build project
        run: cd Frontend && npm run build
        env:
          # Add any environment variables needed for the build
          NODE_ENV: production
          # Ensure Next.js knows to export static files
          NEXT_EXPORT: true
      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "Frontend"
          api_location: ""
          output_location: "out"
          skip_app_build: true # We've already built the app in the previous step
